"""initial schema

Revision ID: f6179be56627
Revises: 
Create Date: 2026-06-26 14:29:43.024298

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6179be56627'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('raw_profile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('rest', 'kafka')", name='ck_raw_profile_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('reconciliation_run',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('list_type', sa.String(), nullable=False),
    sa.Column('old_version', sa.String(), nullable=True),
    sa.Column('new_version', sa.String(), nullable=False),
    sa.Column('clients_rescreened', sa.Integer(), nullable=False),
    sa.Column('newly_flagged', sa.Integer(), nullable=False),
    sa.Column('newly_cleared', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("list_type IN ('sanctions', 'pep', 'adverse_media')", name='ck_reconciliation_list_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening',
    sa.Column('screening_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('profile_hash', sa.String(), nullable=False),
    sa.Column('list_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('screened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('completed', 'failed')", name='ck_screening_status'),
    sa.PrimaryKeyConstraint('screening_id')
    )
    op.create_table('watchlist_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('list_type', sa.String(), nullable=False),
    sa.Column('list_version', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dob_iso', sa.Date(), nullable=True),
    sa.Column('country_iso2', sa.String(length=2), nullable=True),
    sa.Column('risk_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("list_type IN ('sanctions', 'pep', 'adverse_media')", name='ck_watchlist_list_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('screening_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('list_type', sa.String(), nullable=False),
    sa.Column('watchlist_entry_id', sa.String(), nullable=True),
    sa.Column('matched_name', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('dob_match', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("list_type IN ('sanctions', 'pep', 'adverse_media')", name='ck_match_list_type'),
    sa.CheckConstraint('score >= 0 AND score <= 1', name='ck_match_score_range'),
    sa.ForeignKeyConstraint(['screening_id'], ['screening.screening_id'], ),
    sa.ForeignKeyConstraint(['watchlist_entry_id'], ['watchlist_entry.id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('normalized_profile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('profile_hash', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('name_parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dob_iso', sa.Date(), nullable=True),
    sa.Column('nationality_iso2', sa.String(length=2), nullable=True),
    sa.Column('residence_iso2', sa.String(length=2), nullable=True),
    sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['raw_profile.client_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'profile_hash', name='uq_normalized_client_hash')
    )
    op.create_table('decision',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('screening_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_match_id', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('CLEAR', 'FLAG', 'ESCALATE')", name='ck_decision_outcome'),
    sa.ForeignKeyConstraint(['screening_id'], ['screening.screening_id'], ),
    sa.ForeignKeyConstraint(['top_match_id'], ['match.match_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('screening_id')
    )
    op.create_table('audit',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.decision_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    # ### end Alembic commands ###

    # ── Append-only enforcement on `audit` (hard rule #6 / doc 02 §4.7) ───────
    # A trigger rejects every UPDATE/DELETE so the evidence trail is immutable.
    # This trigger is itself a test target (doc 02 §7 "Audit immutability").
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_reject_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit is append-only: % is not permitted', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_append_only
        BEFORE UPDATE OR DELETE ON audit
        FOR EACH ROW EXECUTE FUNCTION audit_reject_mutation();
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_audit_append_only ON audit;")
    op.execute("DROP FUNCTION IF EXISTS audit_reject_mutation();")
    op.drop_table('audit')
    op.drop_table('decision')
    op.drop_table('normalized_profile')
    op.drop_table('match')
    op.drop_table('watchlist_entry')
    op.drop_table('screening')
    op.drop_table('reconciliation_run')
    op.drop_table('raw_profile')
    op.drop_table('idempotency')
    # ### end Alembic commands ###
